# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  funlen:
    lines: 80
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - lll
    - maligned
    - gochecknoglobals
    - gomnd
    - wrapcheck
    - paralleltest
    - forbidigo
    - nlreturn
    - exhaustivestruct
    - interfacer # deprecated
    - forcetypeassert
    - scopelint # deprecated
    - ifshort # too many false positives
    - golint # deprecated
    - varnamelen
    - tagliatelle
    - errname
    - ireturn
    - exhaustruct
    - nonamedreturns
    - wsl
    - gofumpt

issues:
  exclude-use-default: true
  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
    - "exported (type|method|function) (.+) should have comment or be unexported"
    - "ST1000: at least one file in a package should have a package comment"
  exclude-rules:
    - linters:
        - gomnd
        - goconst
        - goerr113
        - noctx
        - funlen
        - dupl
        - structcheck
        - unused
        - unparam
        - nosnakecase
      path: "_test.go"
    - linters:
        - errcheck # Error checking omitted for brevity.
      path: "example_"

